//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public string UniqueAppRef { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalityID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ParentName { get; set; }
        public string ParentID { get; set; }
        public string ParentEmail { get; set; }
        public string ParentContact { get; set; }
        public int SelectedGrade { get; set; }
        public string SelectedStream { get; set; }
        public byte[] StudentIDDoc { get; set; }
        public byte[] ParentIDDoc { get; set; }
        public byte[] PreviousReportCard { get; set; }
        public byte[] ApplicationForm { get; set; }
        public string ApplicationStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
    }
}
