//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentAttempt()
        {
            this.AssessmentAttemptAnswers = new HashSet<AssessmentAttemptAnswer>();
        }
    
        public int AttemptID { get; set; }
        public int AssessmentID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime AttemptStartTime { get; set; }
        public Nullable<System.DateTime> AttemptEndTime { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public Nullable<decimal> MaxScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentAttemptAnswer> AssessmentAttemptAnswers { get; set; }
        public virtual Assessment Assessment { get; set; }
        public virtual Student Student { get; set; }
    }
}
