//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentAttemptAnswer
    {
        public int AttemptAnswerID { get; set; }
        public int AttemptID { get; set; }
        public int QuestionID { get; set; }
        public string StudentAnswer { get; set; }
        public Nullable<decimal> ScoreAwarded { get; set; }
    
        public virtual AssessmentAttempt AssessmentAttempt { get; set; }
        public virtual AssessmentQuestion AssessmentQuestion { get; set; }
    }
}
