//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookOrder()
        {
            this.DriverAssignments = new HashSet<DriverAssignment>();
            this.Notifications = new HashSet<Notification>();
            this.Returns = new HashSet<Return>();
        }
    
        public int OrderID { get; set; }
        public int BookID { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<decimal> DeliveryLatitude { get; set; }
        public Nullable<decimal> DeliveryLongitude { get; set; }
        public decimal DeliveryFee { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public string Status { get; set; }
        public string CurrentStep { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
        public Nullable<int> DriverID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverAssignment> DriverAssignments { get; set; }
        public virtual BooksForSale BooksForSale { get; set; }
        public virtual User User { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return> Returns { get; set; }
    }
}
