//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowExtension
    {
        public int ExtensionID { get; set; }
        public int ReservationID { get; set; }
        public int RequestedByUserID { get; set; }
        public System.DateTime OldEndAt { get; set; }
        public System.DateTime NewEndAt { get; set; }
        public Nullable<int> AdditionalDays { get; set; }
        public Nullable<decimal> AdditionalFee { get; set; }
        public string Status { get; set; }
        public Nullable<int> DecisionBy { get; set; }
        public Nullable<System.DateTime> DecisionAt { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual BorrowReservation BorrowReservation { get; set; }
        public virtual User User { get; set; }
    }
}
