//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowReminder
    {
        public int ReminderID { get; set; }
        public int ReservationID { get; set; }
        public string Kind { get; set; }
        public System.DateTime ScheduledAt { get; set; }
        public bool Sent { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
    
        public virtual BorrowReservation BorrowReservation { get; set; }
    }
}
