//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowInvoiceLine
    {
        public int LineID { get; set; }
        public int InvoiceID { get; set; }
        public string LineType { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
    
        public virtual BorrowInvoice BorrowInvoice { get; set; }
    }
}
