//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorrowInvoice()
        {
            this.BorrowInvoiceLines = new HashSet<BorrowInvoiceLine>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int InvoiceID { get; set; }
        public int ReservationID { get; set; }
        public int BorrowerUserID { get; set; }
        public decimal AmountBorrowFee { get; set; }
        public decimal AmountLateFee { get; set; }
        public decimal AmountDamageFee { get; set; }
        public decimal AmountLostFee { get; set; }
        public decimal OtherFee { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Status { get; set; }
        public System.DateTime IssuedAt { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
        public string PaymentRef { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowInvoiceLine> BorrowInvoiceLines { get; set; }
        public virtual BorrowReservation BorrowReservation { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
