//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorrowReservation()
        {
            this.BorrowAuditLogs = new HashSet<BorrowAuditLog>();
            this.BorrowExtensions = new HashSet<BorrowExtension>();
            this.BorrowInvoices = new HashSet<BorrowInvoice>();
            this.BorrowReminders = new HashSet<BorrowReminder>();
            this.BorrowReservationPhotos = new HashSet<BorrowReservationPhoto>();
            this.DamageReports = new HashSet<DamageReport>();
            this.LossCases = new HashSet<LossCas>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int ReservationID { get; set; }
        public int BookID { get; set; }
        public int BorrowerUserID { get; set; }
        public int LenderUserID { get; set; }
        public System.DateTime StartAt { get; set; }
        public System.DateTime EndAt { get; set; }
        public Nullable<System.DateTime> DueAt { get; set; }
        public decimal FeePerDaySnapshot { get; set; }
        public decimal LateFeePerDaySnapshot { get; set; }
        public Nullable<int> PlannedDays { get; set; }
        public Nullable<decimal> PlannedBorrowFee { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReturnAt { get; set; }
        public Nullable<int> ActualUsageDays { get; set; }
        public Nullable<int> LateDays { get; set; }
        public Nullable<decimal> BorrowFeeFinal { get; set; }
        public Nullable<decimal> LateFeeFinal { get; set; }
        public Nullable<decimal> DamageFee { get; set; }
        public Nullable<decimal> LostFee { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public Nullable<int> AdminReviewerID { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public bool IsOverdue { get; set; }
        public bool DisputeFlag { get; set; }
        public Nullable<System.DateTime> SuspectedLostAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual BooksForSale BooksForSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowAuditLog> BorrowAuditLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowExtension> BorrowExtensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowInvoice> BorrowInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowReminder> BorrowReminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowReservationPhoto> BorrowReservationPhotos { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageReport> DamageReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LossCas> LossCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
