//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageSeverityPolicy
    {
        public string Severity { get; set; }
        public decimal PercentOfBookPrice { get; set; }
    }
}
