//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DamageReport()
        {
            this.DamageReportImages = new HashSet<DamageReportImage>();
        }
    
        public int ReportID { get; set; }
        public int ReservationID { get; set; }
        public int ReporterUserID { get; set; }
        public string Severity { get; set; }
        public string DamageType { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual BorrowReservation BorrowReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageReportImage> DamageReportImages { get; set; }
        public virtual User User { get; set; }
    }
}
