//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.BookOrders = new HashSet<BookOrder>();
            this.DriverAssignments = new HashSet<DriverAssignment>();
            this.DriverAvailabilityLogs = new HashSet<DriverAvailabilityLog>();
            this.DriverLocationLogs = new HashSet<DriverLocationLog>();
        }
    
        public int DriverID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public string VehicleType { get; set; }
        public string LicenseNo { get; set; }
        public System.DateTime LicenseExpiry { get; set; }
        public int MaxDailyDeliveries { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> LastKnownLatitude { get; set; }
        public Nullable<decimal> LastKnownLongitude { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookOrder> BookOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverAssignment> DriverAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverAvailabilityLog> DriverAvailabilityLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverLocationLog> DriverLocationLogs { get; set; }
    }
}
