//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverAssignment
    {
        public int AssignmentID { get; set; }
        public int OrderID { get; set; }
        public int DriverID { get; set; }
        public int AssignedBy { get; set; }
        public System.DateTime AssignedAt { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string Notes { get; set; }
    
        public virtual BookOrder BookOrder { get; set; }
        public virtual User User { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
