//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLocationLog
    {
        public int LogID { get; set; }
        public int DriverID { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
