//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumPost
    {
        public int PostID { get; set; }
        public int ThreadID { get; set; }
        public int PostedBy { get; set; }
        public string PostContent { get; set; }
        public System.DateTime PostedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ForumThread ForumThread { get; set; }
    }
}
