//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LossCas
    {
        public int CaseID { get; set; }
        public int ReservationID { get; set; }
        public System.DateTime DeclaredAt { get; set; }
        public string InvestigationNotes { get; set; }
        public decimal ReplacementValue { get; set; }
        public Nullable<System.DateTime> FinalizedAt { get; set; }
    
        public virtual BorrowReservation BorrowReservation { get; set; }
    }
}
