//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HighschoolDbEntities2 : DbContext
    {
        public HighschoolDbEntities2()
            : base("name=HighschoolDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<AssessmentAttemptAnswer> AssessmentAttemptAnswers { get; set; }
        public virtual DbSet<AssessmentAttempt> AssessmentAttempts { get; set; }
        public virtual DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<BookImage> BookImages { get; set; }
        public virtual DbSet<BookOrder> BookOrders { get; set; }
        public virtual DbSet<BooksForSale> BooksForSales { get; set; }
        public virtual DbSet<BorrowAuditLog> BorrowAuditLogs { get; set; }
        public virtual DbSet<BorrowExtension> BorrowExtensions { get; set; }
        public virtual DbSet<BorrowInvoiceLine> BorrowInvoiceLines { get; set; }
        public virtual DbSet<BorrowInvoice> BorrowInvoices { get; set; }
        public virtual DbSet<BorrowReminder> BorrowReminders { get; set; }
        public virtual DbSet<BorrowReservationPhoto> BorrowReservationPhotos { get; set; }
        public virtual DbSet<BorrowReservation> BorrowReservations { get; set; }
        public virtual DbSet<DamageReportImage> DamageReportImages { get; set; }
        public virtual DbSet<DamageReport> DamageReports { get; set; }
        public virtual DbSet<DamageSeverityPolicy> DamageSeverityPolicies { get; set; }
        public virtual DbSet<DriverAssignment> DriverAssignments { get; set; }
        public virtual DbSet<DriverAvailabilityLog> DriverAvailabilityLogs { get; set; }
        public virtual DbSet<DriverLocationLog> DriverLocationLogs { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<ForumPost> ForumPosts { get; set; }
        public virtual DbSet<ForumThread> ForumThreads { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<GradeSubject> GradeSubjects { get; set; }
        public virtual DbSet<GradeSubjectTeacher> GradeSubjectTeachers { get; set; }
        public virtual DbSet<LossCas> LossCases { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ReturnImage> ReturnImages { get; set; }
        public virtual DbSet<Return> Returns { get; set; }
        public virtual DbSet<ReturnsAuditLog> ReturnsAuditLogs { get; set; }
        public virtual DbSet<SessionAttendance> SessionAttendances { get; set; }
        public virtual DbSet<SessionFeedback> SessionFeedbacks { get; set; }
        public virtual DbSet<SessionReminder> SessionReminders { get; set; }
        public virtual DbSet<Stream> Streams { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentTransferRequest> StudentTransferRequests { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TeacherAllocationHistory> TeacherAllocationHistories { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TransferRequestAuditLog> TransferRequestAuditLogs { get; set; }
        public virtual DbSet<TransferRequestFile> TransferRequestFiles { get; set; }
        public virtual DbSet<TransferRequestTimetablePreview> TransferRequestTimetablePreviews { get; set; }
        public virtual DbSet<TutorClassEnrollment> TutorClassEnrollments { get; set; }
        public virtual DbSet<TutorClass> TutorClasses { get; set; }
        public virtual DbSet<TutorClassExitHistory> TutorClassExitHistories { get; set; }
        public virtual DbSet<TutorClassForum> TutorClassForums { get; set; }
        public virtual DbSet<TutorClassResource> TutorClassResources { get; set; }
        public virtual DbSet<TutorGradeSubject> TutorGradeSubjects { get; set; }
        public virtual DbSet<TutorPrivateBooking> TutorPrivateBookings { get; set; }
        public virtual DbSet<Tutor> Tutors { get; set; }
        public virtual DbSet<TutorSession> TutorSessions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserWallet> UserWallets { get; set; }
        public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }
        public virtual DbSet<UserBalance> UserBalances { get; set; }
        public virtual DbSet<UserCreditsLog> UserCreditsLogs { get; set; }
        public virtual DbSet<vwBorrowActive> vwBorrowActives { get; set; }
        public virtual DbSet<vwBorrowOverdue> vwBorrowOverdues { get; set; }
        public virtual DbSet<vwOrdersAwaitingDriver> vwOrdersAwaitingDrivers { get; set; }
    }
}
