//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> RelatedSessionID { get; set; }
        public Nullable<int> TransferRequestID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ReservationID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    
        public virtual BookOrder BookOrder { get; set; }
        public virtual BorrowInvoice BorrowInvoice { get; set; }
        public virtual BorrowReservation BorrowReservation { get; set; }
        public virtual StudentTransferRequest StudentTransferRequest { get; set; }
        public virtual User User { get; set; }
    }
}
