//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnsAuditLog
    {
        public long AuditID { get; set; }
        public int ReturnID { get; set; }
        public string Action { get; set; }
        public Nullable<int> PerformedBy { get; set; }
        public string PerformedByRole { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string Comment { get; set; }
        public string SnapshotBefore { get; set; }
        public string SnapshotAfter { get; set; }
    
        public virtual Return Return { get; set; }
    }
}
