//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Return()
        {
            this.ReturnImages = new HashSet<ReturnImage>();
            this.ReturnsAuditLogs = new HashSet<ReturnsAuditLog>();
        }
    
        public int ReturnID { get; set; }
        public int OrderID { get; set; }
        public int BuyerUserID { get; set; }
        public int SellerUserID { get; set; }
        public string Reason { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public decimal RefundAmountBookValue { get; set; }
        public decimal RefundAmountDelivery { get; set; }
        public Nullable<decimal> RefundTotal { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string AdminComment { get; set; }
        public Nullable<System.DateTime> DecisionAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual BookOrder BookOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnImage> ReturnImages { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnsAuditLog> ReturnsAuditLogs { get; set; }
    }
}
