//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnImage
    {
        public int ImageID { get; set; }
        public int ReturnID { get; set; }
        public string FileName { get; set; }
        public string MimeType { get; set; }
        public byte[] ImageBytes { get; set; }
        public System.DateTime UploadedAt { get; set; }
    
        public virtual Return Return { get; set; }
    }
}
