//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionFeedback
    {
        public int FeedbackID { get; set; }
        public Nullable<int> TutorSessionID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public int StudentID { get; set; }
        public int TutorID { get; set; }
        public int Rating { get; set; }
        public string Feedback { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual TutorPrivateBooking TutorPrivateBooking { get; set; }
        public virtual TutorSession TutorSession { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
