//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionReminder
    {
        public int ReminderID { get; set; }
        public int StudentID { get; set; }
        public int TutorSessionID { get; set; }
        public bool ReminderSent { get; set; }
        public Nullable<System.DateTime> ReminderSentTime { get; set; }
    
        public virtual TutorSession TutorSession { get; set; }
        public virtual Student Student { get; set; }
    }
}
