//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTransferRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTransferRequest()
        {
            this.Notifications = new HashSet<Notification>();
            this.TransferRequestAuditLogs = new HashSet<TransferRequestAuditLog>();
            this.TransferRequestFiles = new HashSet<TransferRequestFile>();
            this.TransferRequestTimetablePreviews = new HashSet<TransferRequestTimetablePreview>();
        }
    
        public int TransferRequestID { get; set; }
        public int StudentID { get; set; }
        public string OldStream { get; set; }
        public string NewStream { get; set; }
        public int OldGrade { get; set; }
        public int NewGrade { get; set; }
        public string Justification { get; set; }
        public Nullable<int> AttachmentFileID { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string TeacherComment { get; set; }
        public Nullable<System.DateTime> TeacherActionDate { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string AdminComment { get; set; }
        public Nullable<System.DateTime> AdminActionDate { get; set; }
        public bool Escalated { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRequestAuditLog> TransferRequestAuditLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRequestFile> TransferRequestFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRequestTimetablePreview> TransferRequestTimetablePreviews { get; set; }
    }
}
