//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AssessmentAttempts = new HashSet<AssessmentAttempt>();
            this.SessionAttendances = new HashSet<SessionAttendance>();
            this.SessionFeedbacks = new HashSet<SessionFeedback>();
            this.SessionReminders = new HashSet<SessionReminder>();
            this.TutorClassExitHistories = new HashSet<TutorClassExitHistory>();
            this.TutorPrivateBookings = new HashSet<TutorPrivateBooking>();
            this.StudentTransferRequests = new HashSet<StudentTransferRequest>();
            this.TutorClassEnrollments = new HashSet<TutorClassEnrollment>();
        }
    
        public int StudentID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalityID { get; set; }
        public int Grade { get; set; }
        public string Stream { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ParentName { get; set; }
        public string ParentID { get; set; }
        public string ParentEmail { get; set; }
        public string ParentContact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentAttempt> AssessmentAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionAttendance> SessionAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionFeedback> SessionFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionReminder> SessionReminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorClassExitHistory> TutorClassExitHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorPrivateBooking> TutorPrivateBookings { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTransferRequest> StudentTransferRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorClassEnrollment> TutorClassEnrollments { get; set; }
    }
}
