//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAllocationHistory
    {
        public int HistoryID { get; set; }
        public int TeacherID { get; set; }
        public int GradeID { get; set; }
        public int StreamID { get; set; }
        public int SubjectID { get; set; }
        public System.DateTime AllocationDate { get; set; }
        public Nullable<int> AllocatedBy { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Stream Stream { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
