//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferRequestAuditLog
    {
        public int AuditID { get; set; }
        public int TransferRequestID { get; set; }
        public string Action { get; set; }
        public Nullable<int> PerformedBy { get; set; }
        public string PerformedByRole { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string Comment { get; set; }
        public string BeforeState { get; set; }
        public string AfterState { get; set; }
    
        public virtual StudentTransferRequest StudentTransferRequest { get; set; }
    }
}
