//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferRequestTimetablePreview
    {
        public int PreviewID { get; set; }
        public int TransferRequestID { get; set; }
        public string OldSchedule { get; set; }
        public string NewSchedule { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual StudentTransferRequest StudentTransferRequest { get; set; }
    }
}
