//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferRequestFile
    {
        public int FileID { get; set; }
        public int TransferRequestID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] FileContent { get; set; }
        public System.DateTime UploadedAt { get; set; }
        public int UploadedBy { get; set; }
    
        public virtual StudentTransferRequest StudentTransferRequest { get; set; }
    }
}
