//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorClassExitHistory
    {
        public int ExitID { get; set; }
        public int EnrollmentID { get; set; }
        public int StudentID { get; set; }
        public int TutorClassID { get; set; }
        public string ExitReason { get; set; }
        public System.DateTime ExitDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual TutorClassEnrollment TutorClassEnrollment { get; set; }
        public virtual TutorClass TutorClass { get; set; }
    }
}
