//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorSession()
        {
            this.SessionAttendances = new HashSet<SessionAttendance>();
            this.SessionFeedbacks = new HashSet<SessionFeedback>();
            this.SessionReminders = new HashSet<SessionReminder>();
        }
    
        public int TutorSessionID { get; set; }
        public Nullable<int> TutorClassID { get; set; }
        public int TutorID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int SubjectID { get; set; }
        public int GradeID { get; set; }
        public System.DateTime SessionDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Location { get; set; }
        public string OnlineMeetingLink { get; set; }
        public string Mode { get; set; }
        public string Resources { get; set; }
        public bool IsCancelled { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Grade Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionAttendance> SessionAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionFeedback> SessionFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionReminder> SessionReminders { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual TutorClass TutorClass { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
