//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorClassEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorClassEnrollment()
        {
            this.TutorClassExitHistories = new HashSet<TutorClassExitHistory>();
        }
    
        public int EnrollmentID { get; set; }
        public int TutorClassID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string Status { get; set; }
        public string ExitReason { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorClassExitHistory> TutorClassExitHistories { get; set; }
        public virtual TutorClass TutorClass { get; set; }
    }
}
