//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorClassResource
    {
        public int ResourceID { get; set; }
        public int TutorClassID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] FileContent { get; set; }
        public int UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string Description { get; set; }
    
        public virtual TutorClass TutorClass { get; set; }
    }
}
