//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorPrivateBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorPrivateBooking()
        {
            this.SessionAttendances = new HashSet<SessionAttendance>();
            this.SessionFeedbacks = new HashSet<SessionFeedback>();
        }
    
        public int BookingID { get; set; }
        public int TutorID { get; set; }
        public int StudentID { get; set; }
        public int SubjectID { get; set; }
        public int GradeID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Status { get; set; }
        public System.DateTime RequestedAt { get; set; }
        public Nullable<System.DateTime> AcceptedAt { get; set; }
        public Nullable<System.DateTime> RejectedAt { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
        public string Topic { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public bool IsPaid { get; set; }
    
        public virtual Grade Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionAttendance> SessionAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionFeedback> SessionFeedbacks { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
