//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorClass()
        {
            this.TutorClassEnrollments = new HashSet<TutorClassEnrollment>();
            this.TutorClassExitHistories = new HashSet<TutorClassExitHistory>();
            this.TutorClassForums = new HashSet<TutorClassForum>();
            this.TutorClassResources = new HashSet<TutorClassResource>();
            this.TutorSessions = new HashSet<TutorSession>();
        }
    
        public int TutorClassID { get; set; }
        public int TutorID { get; set; }
        public int GradeID { get; set; }
        public int SubjectID { get; set; }
        public string ClassName { get; set; }
        public string ClassDescription { get; set; }
        public int Capacity { get; set; }
        public decimal AnnualFee { get; set; }
        public byte[] CoverImage { get; set; }
        public string Location { get; set; }
        public string Mode { get; set; }
        public Nullable<System.DateTime> EnrollmentDeadline { get; set; }
        public string EntryRequirements { get; set; }
        public string WhatsAppContact { get; set; }
        public string ScheduleTemplate { get; set; }
        public string ResourcesFolder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorClassEnrollment> TutorClassEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorClassExitHistory> TutorClassExitHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorClassForum> TutorClassForums { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorClassResource> TutorClassResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorSession> TutorSessions { get; set; }
    }
}
