//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBorrowOverdue
    {
        public int ReservationID { get; set; }
        public int BookID { get; set; }
        public int BorrowerUserID { get; set; }
        public Nullable<System.DateTime> DueAt { get; set; }
        public System.DateTime NowAt { get; set; }
        public Nullable<int> DaysOverdue { get; set; }
    }
}
