//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrdersAwaitingDriver
    {
        public int OrderID { get; set; }
        public int BookID { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
        public string DeliveryAddress { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
