//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avonford_Secondary_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransaction
    {
        public long TxID { get; set; }
        public int UserID { get; set; }
        public decimal Amount { get; set; }
        public string Direction { get; set; }
        public string Reason { get; set; }
        public string RefType { get; set; }
        public Nullable<int> RefID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<decimal> BeforeBalance { get; set; }
        public Nullable<decimal> AfterBalance { get; set; }
        public string Notes { get; set; }
    
        public virtual User User { get; set; }
    }
}
